/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: songsong16.c                                              *
* Font:        songsong                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\24751\Desktop\zi.txt                   *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsong16;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_56DE[ 32] = { /* code 56DE */
  ________,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __X_____,____X___,
  __X__XXX,XX__X___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X__XXX,XX__X___,
  __X_____,____X___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5B9A[ 32] = { /* code 5B9A */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X_______,_____X__,
  ________,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  ___X___X,________,
  ___X___X,XXXXX___,
  ___X___X,________,
  ___X___X,________,
  __X_X__X,________,
  _X___XXX,XXXXXXX_,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_786E[ 32] = { /* code 786E */
  ________,_X______,
  ________,_X______,
  XXXXXX__,_XXXXX__,
  ___X____,X____X__,
  ___X___X,____X___,
  __X___X_,XXXXXXX_,
  __XXXX__,X__X__X_,
  _XX__X__,X__X__X_,
  _XX__X__,XXXXXXX_,
  X_X__X__,X__X__X_,
  __X__X__,X__X__X_,
  __X__X__,XXXXXXX_,
  __XXXX__,X__X__X_,
  __X__X_X,___X__X_,
  __X____X,____X_X_,
  ______X_,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_8FD4[ 32] = { /* code 8FD4 */
  ________,____X___,
  __X_____,__XXXX__,
  ___X__XX,XX______,
  ___X__X_,________,
  ______X_,________,
  ______XX,XXXXXX__,
  XXXX__X_,_____X__,
  ___X__X_,X___X___,
  ___X__X_,_X_X____,
  ___X__X_,__X_____,
  ___X__X_,_X_X____,
  ___X_X__,X___X___,
  ___X_X_X,_____X__,
  __X_X___,________,
  _X___XXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontsong16_CharInfo[4] = {
   {  16,  16,  2, acGUI_Fontsong16_56DE } /* code 56DE */
  ,{  16,  16,  2, acGUI_Fontsong16_5B9A } /* code 5B9A */
  ,{  16,  16,  2, acGUI_Fontsong16_786E } /* code 786E */
  ,{  16,  16,  2, acGUI_Fontsong16_8FD4 } /* code 8FD4 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop4 = {
   0x8FD4 /* first character */
  ,0x8FD4 /* last character  */
  ,&GUI_Fontsong16_CharInfo[  3] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop3 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_Fontsong16_CharInfo[  2] /* address of first character */
  ,&GUI_Fontsong16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop2 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_Fontsong16_CharInfo[  1] /* address of first character */
  ,&GUI_Fontsong16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop1 = {
   0x56DE /* first character */
  ,0x56DE /* last character  */
  ,&GUI_Fontsong16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsong16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsong16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsong16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

